### ISSUE TITLE
Flag -e not working (version v3.6.0-alpha)

### ISSUE THREAD

**Issue by dalmena** [turnerlabs/cstore#5]
On version v3.6.0-alpha the flag -e no longer adds the export keyword in front of the variables.

Only noticed on version 3.6, but it could have affected other versions as well.

**Comment by kendavis2** [comment]
The `-e` flag changed to `-g terminal-export` per the release notes in version v3.4.0-alpha. Next time, I may need to make this a major version update since it can break some functionality that apps depend on when upgrading.

**Comment by dalmena** [comment]
As per release 3.4. This flag has changed a bit:

`-e changed to the formatting flag -g terminal-export as the -e flag now exports raw configs`
