### ISSUE TITLE
Go (direct) implementation error

### ISSUE THREAD

**Issue by BartAlcorn** [turnerlabs/cstore#6]
Referencing: /docs/LIBRARY.md, the Go (direct) instructions result in the following error: 

`import "github.com/turnerlabs/cstore" is a program, not an importable package`

**Comment by kendavis2** [comment]
Not sure when the library import stopped working; however, I am migrating this repo to the officially support Go versioning model which appears to correct the issue. However, this will necessitate the a new major version of cStore v4 since I cannot move previously tagged v3 commits.

**Comment by kendavis2** [comment]
The import statement will be `import "github.com/turnerlabs/cstore/v4"` going forward.
